Repository GDSC-CGC/CPP, pull requests merged in 2022-10, with the labels that each got.

#2 Task 2 done
  Submissions/2121506_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#6 Task 1 done
  Submissions/2121466_task1
Labels: good first issue, hacktoberfest-accepted

#5 Task2 2002848
  Submissions/2002848_task2/task2.cpp
  Submissions/2002848_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#4 2002566_task1
  Submissions/2002566_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#8 Task 3 done
  Submissions/2121506_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#7 Updated Contribution.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest-accepted

#10 Create 2019030_task1
  Submissions/2019030_task1
Labels: good first issue, hacktoberfest-accepted

#13 Create task_1.cpp
  Submissions/2018898_task_1/task_1.cpp
Labels: good first issue, hacktoberfest-accepted

#16 Create task2.cpp
  Submissions/2121481_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#12 Create 2121475-task1
  Submissions/2121475_task1/2121475-task1.cpp
Labels: good first issue, hacktoberfest-accepted

#11 Create 2019030_task2
  Submissions/2019030_task2
Labels: good first issue, hacktoberfest-accepted

#17 Create 2018955_task01
  Submissions/2018955_task01/2018955_task01.cpp
  Submissions/2018955_task02/2018955_task02.cpp
Labels: good first issue, hacktoberfest-accepted

#20 task2.cpp
  2002566_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#19 Create 2019198 task1
  Submissions/2019198_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#18 Create 2019030_task3
  Submissions/2019030_task3
Labels: good first issue, hacktoberfest-accepted

#22 Create task1.cpp
  Submissions/2121525_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#23 Create 2019030_task4
  Submissions/2019030_task4
Labels: good first issue, hacktoberfest-accepted

#24 Create task4.cpp
  Submissions/2121506_task4/task4.cpp
Labels: good first issue, hacktoberfest-accepted

#25 Create task3.cpp
  Submissions/2121481_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#27 task 3
  Submissions/2018898_task_3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#28 Create task1
  Submissions/2121239_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#29 Add files via upload
  Submissions/2003203_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#39 Add files via upload
  Submissions/2018950_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#58 Create 2121516-task1
  Submissions/2121516_task1/2121516-task1.cpp
Labels: good first issue, hacktoberfest-accepted

#38 Create task1.cpp
  Submissions/211536_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#40 Create task1.cpp
  Submissions/2002567_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#46 Add files via upload
  Submissions/2001703_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#47 2003227_task1
  Submissions/2003227_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#49 Create task1.cpp
  Submissions/201160_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#56 Create 2018919_task01
  Submissions/2018919_task01/2018919_task01.cpp
Labels: good first issue, hacktoberfest-accepted

#65 Created task1.cpp
  Submissions/2002338_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#66 solved task1
  Submissions/2018844_task1/task1.cpp
  Submissions/2018844_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#55 Create task4.cpp
  Submissions/2018898_task_4/task4.cpp
  Submissions/2018898_task_5/task5.cpp
Labels: good first issue, hacktoberfest-accepted

#82 Create 2019027_Task1
  Submissions/2019027_Task1
Labels: good first issue, hacktoberfest-accepted

#32 Create 2121490-task2
  Submissions/2121490_task2/2121490-task2
Labels: good first issue, hacktoberfest-accepted

#33 Create 2121490-task3
  Submissions/2121490_task3/2121490-task3
Labels: good first issue, hacktoberfest-accepted

#78 Create task2.cpp
  Submissions/2018898_task_2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#93 Task 2 done
  Submissions/2121466_Task4/task4.cpp
  Submissions/2121466_task2
  Submissions/2121466_task3
Labels: good first issue, hacktoberfest-accepted

#62 Create 2018919_task03.cpp
  Submissions/2018919_task03/2018919_task03.cpp
Labels: good first issue, hacktoberfest-accepted

#64 Create 2018919_task05
  Submissions/2018919_task05/2018919_task05.cpp
Labels: good first issue, hacktoberfest-accepted

#48 Add files via upload
  2001267_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#34 Create 2121490-task4
  Submissions/2121490_task4/2121490-task4
Labels: good first issue, hacktoberfest-accepted

#43 Create task3
  Submissions/2121239_task3/task3
Labels: good first issue, hacktoberfest-accepted

#57 Create 2018919_task02
  Submissions/2018919_task02/2018919_task02.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#89 Add files via upload
  Submissions/2002768_task2/2002768_task2.cpp
  Submissions/2002768_task3/2002768_task3.cpp
  Submissions/2002768_task4/2002768_task4.cpp
Labels: good first issue, hacktoberfest-accepted

#111 Task 4 done
  Submissions/2121466_Task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#101 Create 2121475-task4
  Submissions/2121475_task4/2121475-task4.cpp
Labels: good first issue, hacktoberfest-accepted

#45 Create task5.cpp
  Submissions/2121239_task5/task5.cpp
Labels: good first issue, hacktoberfest-accepted

#107 Create task_2
  Submissions/2018936_task2/task_2.cpp
  Submissions/2018936_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#96 Create 2018955_task03
  Submissions/2018955_task03/2018955_task03.cpp
Labels: good first issue, hacktoberfest-accepted

#36 2121525-task3.cpp
  Submissions/2121525_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#37 2121525-task4.cpp
  Submissions/2121525_task4/task4.cpp
Labels: good first issue, hacktoberfest-accepted

#68 Create task4.cpp
  Submissions/2121481_task4/task4.cpp
Labels: good first issue, hacktoberfest-accepted

#112 Task2.cpp
  Submissions/2018794_task2/task2.cpp
Labels: documentation, good first issue, hacktoberfest-accepted

#86 Create 2121475-task3
  Submissions/2121475_task3/2121475-task3.cpp
Labels: good first issue, hacktoberfest-accepted

#60 Create 2121516-task3
  Submissions/2121516_task3/2121516-task3.cpp
Labels: good first issue, hacktoberfest-accepted

#97 Create 2018955_task04
  Submissions/2018955_task04/2018955_task04.cpp
  Submissions/2018955_task05/2018955_task05.cpp
Labels: good first issue, hacktoberfest-accepted

#61 Create 2121516-task4
  Submissions/2121516_task4/2121516-task4.cpp
Labels: good first issue, hacktoberfest-accepted

#104 Created Task1.cpp within the folder CSC2062_task1
  Submissions/CSC2062_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#113 Create 2121480-task1
  Submissions/2121480-task1/2121480-task1.cpp
Labels: good first issue, hacktoberfest-accepted

#114 Task3.cpp
  Submissions/2018794_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#115 Task4.cpp
  Submissions/2018794_task4/task4.cpp
Labels: good first issue, hacktoberfest-accepted

#116 2121462_task1
  Submissions/2121462_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#92 Create task1.cpp
  Submissions/221411_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#90 19146301_task1
  Submissions/1914301_task1/1914301_task1.cpp
  Submissions/1914301_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#100 create task1
  Submissions/2121665_task/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#63 Create 2018919_task04
  Submissions/2018919_task04/2018919_task04.cpp
Labels: good first issue, hacktoberfest-accepted

#70 Create task2.cpp
  Submissions/211536_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#72 Create task2.cpp
  Submissions/2002567_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#74 Create task2.cpp
  Submissions/2018954_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#76 Create task2.cpp
  Submissions/200338_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#77 Create task2.cpp
  Submissions/201149_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#79 Add files via upload
  Submissions/2001703_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#81 Add files via upload
  Submissions/2003203_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#83 Create task1.cpp
  Submissions/2018964_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#84 2003227_TASK2
  Submissions/2003227_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#87 Create task1.cpp
  Submissions/2018975_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#94 Create 2121462_task2
  Submissions/2121462_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#95 1914651_task1
  Submissions/1914651_task1/task1.ccp
Labels: good first issue, hacktoberfest-accepted

#99 create task_1
  Submissions/2019037_task1/task_1.cpp
Labels: good first issue, hacktoberfest-accepted

#102 Create task1
  Submissions/2101658_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#103 2001267_Task2
  Submissions/2001267_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#105 Add files via upload
  Submissions/2003703_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#106 Create task1.cpp
  Submissions/2002576_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#109 Create 2121666_task1
  Submissions/2121666_task1/2121666_task1.cpp
Labels: good first issue, hacktoberfest-accepted

#118 Create 2121462_task3
  Submissions/2121462_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#120 Create 2121462_task4
  Submissions/2121462_task4/task4.cpp
Labels: good first issue, hacktoberfest-accepted

#121 task 1 done
  Submissions/2002779_task1/2002779_task1
  Submissions/2002779_task1/2002779_task1.cpp
Labels: good first issue, hacktoberfest-accepted

#126 Create task4
  Submissions/2018936_task4/task4.cpp
Labels: good first issue, hacktoberfest-accepted

#127 task2 completed
  Submissions/2121665_task/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#128 1914650_Task 3
  Submissions/1914650_task3/Task3.cpp
  Submissions/1914650_task4/Task4.cpp
Labels: good first issue, hacktoberfest-accepted

#130 Add files via upload
  Submissions/201634_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#132 Create 21task1
  Submissions/21UCS.task1/21task1.cpp
  Submissions/21UCS_task_2/21UCStaks2.cpp
Labels: good first issue, hacktoberfest-accepted

#133 Create task3.cpp
  Submissions/211536_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#149 task1_completed
  Submissions/2019024_tasks/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#146 2003227_task3
  Submissions/2003227_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#142 21UCS_task5
  Submissions/21UCS_task3/21UCS.task3.cpp
  Submissions/21UCS_task4/21UCS.task4.cpp
  Submissions/21UCS_task5/21UCS.task5.cpp
Labels: good first issue, hacktoberfest-accepted

#147 Create task1
  Submissions/2121691_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#140 1914301_task3
  Submissions/1914301_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#151 Create task1
  Submissions/21UCS_task1/task1.cpp
  Submissions/21UCStask2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#145 Add files via upload
  Submissions/2001267_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#144 task3 completed
  Submissions/2121665_task/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#150 Create 2019024_task2
  Submissions/2019024_task1/task1.cpp
  Submissions/2019024_task2/2019024_task2.cpp
Labels: good first issue, hacktoberfest-accepted

#152 Create 21UCS_task2
  Submissions/21UCS_task2/21UCS_task2.cpp
Labels: good first issue, hacktoberfest-accepted

#137 Add files via upload
  Submissions/2001703_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#156 Create 2026995-task1.cpp
  Submissions/2026995-task1/2026995-task1.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#157 Create 2026995-task2.cpp
  Submissions/2026995-task2/2026995-task2.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#161 Create 2121480-task2
  Submissions/2121480_task2/2121480-task2.cpp
Labels: good first issue, hacktoberfest-accepted

#134 task2 submitted
  Submissions/2019037_task2/task_2.cpp
Labels: good first issue, hacktoberfest-accepted

#135 Create 2121666_task2
  Submissions/2121666_task2/2121666_task2.cpp
Labels: good first issue, hacktoberfest-accepted

#167 Create 2121666_task3
  Submissions/2121666_task3/2121666_task3.cpp
Labels: good first issue, hacktoberfest-accepted

#163 task 3 submitted
  Submissions/2019037_task3/task_3.cpp
Labels: good first issue, hacktoberfest-accepted

#166 Create 2019024_task3
  Submissions/2019024_task3/2019024_task3.cpp
Labels: good first issue, hacktoberfest-accepted

#165 2002566_task3.cpp
  Submissions/2002566_task3/2002566_task3.cpp
Labels: good first issue, hacktoberfest-accepted

#162 Create task3
  Submissions/21UCS_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#164 2002488_task1.cpp
  Submissions/2002488_task1/2002488_task1.cpp
Labels: good first issue, hacktoberfest-accepted

#160 1914301_task4
  Submissions/1914301_task4/task4.cpp
Labels: good first issue, hacktoberfest-accepted

#143 Create task3.cpp
  Submissions/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#168 Task 4 submitted
  Submissions/2019037_task4/task_4.cpp
Labels: good first issue, hacktoberfest-accepted

#155 Completed Task-1,2,3,4 and 5
  Submissions/CSE2021035_task1
  Submissions/CSE2021035_task2
  Submissions/CSE2021035_task3
  Submissions/CSE2021035_task4
  Submissions/CSE2021035_task5
Labels: good first issue, hacktoberfest-accepted

#141 Create 2019027_Task3
  Submissions/2019027_Task3
Labels: enhancement, good first issue, hacktoberfest-accepted

#139 Add files via upload
  Submissions/2003203_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#170 Task1 submitted
  Submissions/2019012_task1/Task1.cpp
Labels: good first issue, hacktoberfest-accepted

#169 Task 4 submitted
  Submissions/2121666_task4/2121666_task4.cpp
Labels: good first issue, hacktoberfest-accepted

#173 Task 2
  Submissions/2019012-task2/Task2.cpp
Labels: good first issue, hacktoberfest-accepted

#172 Create 2019024_task4
  Submissions/2019024_task4/2019024_task4.cpp
Labels: good first issue, hacktoberfest-accepted

#174 Task 3
  Submissions/2019012_task3/Task3.cpp
Labels: good first issue, hacktoberfest-accepted

#185 Create task4.cpp
  Submissions/2019027_task4/task4.cpp
Labels: good first issue, hacktoberfest-accepted

#184 1914652_task1
  Submissions/1914652_task1/Task1.cpp
Labels: good first issue, hacktoberfest-accepted

#183 Create task4.cpp
  Submissions/211536_task4/task4.cpp
Labels: good first issue, hacktoberfest-accepted

#179 Task4
  Submissions/2019012_task4/Task4.cpp
Labels: good first issue, hacktoberfest-accepted

#182 2002567_task3.cpp
  Submissions/2002567_task3/2002567_task3.cpp
Labels: good first issue, hacktoberfest-accepted

#181 2002488_task2.cpp
  Submissions/2002488_task2/2002488_task2.cpp
Labels: good first issue, hacktoberfest-accepted

#186 Create task1.cpp
  Submissions/201153_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#188 Create 2121480-task3
  Submissions/2121480-task4/task4.cpp
  Submissions/2121480_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#192 2002488_task3.cpp
  Submissions/2002488_task3/2002488_task3.cpp
Labels: good first issue, hacktoberfest-accepted

#191 2002563_task1.cpp
  Submissions/2002563_task1/2002563_task1.cpp
Labels: good first issue, hacktoberfest-accepted

#190 Create task2.cpp
  Submissions/2018975_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#187 2018964_task2.cpp
  Submissions/2018964_task2/2018964_task2.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#189 Create task2.cpp
  Submissions/201153_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#193 Create task3.cpp
  Submissions/2018975_task3/task3.cpp
Labels: good first issue, hacktoberfest-accepted

#199 1914651 task2
  Submissions/1914651_task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#198 task3
  2121480-task2/task2.cpp
Labels: good first issue, hacktoberfest-accepted

#197 task1
  2121480-task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#196 Create task1.cpp
  Submissions/2018968_task1/task1.cpp
Labels: good first issue, hacktoberfest-accepted

#195 Create task3.cpp
  Submissions/201153_task3/task3.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#194 Create task3.cpp
  Submissions/2018964_task3/task3.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#205 Create 2019020_task1
  Submissions/2019020_task1
Labels: good first issue, hacktoberfest-accepted

#206 Create 2019020_task2
  Submissions/2019020_task2
Labels: good first issue, hacktoberfest-accepted

#207 Create task_3
  Submissions/2018936_task3/task_3.cpp
Labels: good first issue, hacktoberfest-accepted
